[2024-12-05T20:54:05.335+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T20:54:05.345+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brand_category_mapping.execute_sql manual__2024-12-05T20:53:43.542267+00:00 [queued]>
[2024-12-05T20:54:05.351+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brand_category_mapping.execute_sql manual__2024-12-05T20:53:43.542267+00:00 [queued]>
[2024-12-05T20:54:05.352+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2024-12-05T20:54:05.363+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): execute_sql> on 2024-12-05 20:53:43.542267+00:00
[2024-12-05T20:54:05.368+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2450) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T20:54:05.369+0000] {standard_task_runner.py:72} INFO - Started process 2451 to run task
[2024-12-05T20:54:05.370+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'brand_category_mapping', 'execute_sql', 'manual__2024-12-05T20:53:43.542267+00:00', '--job-id', '544', '--raw', '--subdir', 'DAGS_FOLDER/llm_mapping.py', '--cfg-path', '/tmp/tmp1fxv5_jz']
[2024-12-05T20:54:05.371+0000] {standard_task_runner.py:105} INFO - Job 544: Subtask execute_sql
[2024-12-05T20:54:05.402+0000] {task_command.py:467} INFO - Running <TaskInstance: brand_category_mapping.execute_sql manual__2024-12-05T20:53:43.542267+00:00 [running]> on host c7780884450d
[2024-12-05T20:54:05.458+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='artzsh' AIRFLOW_CTX_DAG_ID='brand_category_mapping' AIRFLOW_CTX_TASK_ID='execute_sql' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T20:53:43.542267+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T20:53:43.542267+00:00'
[2024-12-05T20:54:05.459+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T20:54:05.476+0000] {llm_mapping.py:235} INFO - Извлечён sql_code: INSERT INTO DDS.brand_category_mapping (brand, category_index) VALUES
    ('aardwolf', 'accessories'),
    ('abaybooks', 'stationery'),
    ('abc', 'stationery'),
    ('abhika', 'apparel'),
    ('abk', 'apparel'),
    ('abris', 'construction'),
    ('absolutechampion', 'sport'),
    ('absolutenewyork', 'apparel'),
    ('abtoys', 'kids'),
    ('abugarcia', 'sport'),
    ('academie', 'medicine'),
    ('acana', 'medicine'),
    ('a-case', 'accessories'),
    ('acase', 'accessories'),
    ('accesstyle', 'accessories'),
    ('accumaster', 'appliances'),
    ('acd', 'electronics'),
    ('acebeam', 'electronics'),
    ('acer', 'computers'),
    ('aces', 'electronics'),
    ('achilles', 'apparel'),
    ('acm', 'electronics'),
    ('acme', 'appliances'),
    ('acnecontrolprofessional', 'medicine'),
    ('acoola', 'apparel');
[2024-12-05T20:54:05.482+0000] {base.py:84} INFO - Retrieving connection 'database_cloud'
[2024-12-05T20:54:06.277+0000] {llm_mapping.py:214} INFO - Выполнение SQL-кода:
INSERT INTO DDS.brand_category_mapping (brand, category_index) VALUES
    ('aardwolf', 'accessories'),
    ('abaybooks', 'stationery'),
    ('abc', 'stationery'),
    ('abhika', 'apparel'),
    ('abk', 'apparel'),
    ('abris', 'construction'),
    ('absolutechampion', 'sport'),
    ('absolutenewyork', 'apparel'),
    ('abtoys', 'kids'),
    ('abugarcia', 'sport'),
    ('academie', 'medicine'),
    ('acana', 'medicine'),
    ('a-case', 'accessories'),
    ('acase', 'accessories'),
    ('accesstyle', 'accessories'),
    ('accumaster', 'appliances'),
    ('acd', 'electronics'),
    ('acebeam', 'electronics'),
    ('acer', 'computers'),
    ('aces', 'electronics'),
    ('achilles', 'apparel'),
    ('acm', 'electronics'),
    ('acme', 'appliances'),
    ('acnecontrolprofessional', 'medicine'),
    ('acoola', 'apparel');
[2024-12-05T20:54:06.363+0000] {llm_mapping.py:220} ERROR - Ошибка при выполнении SQL-кода: relation "dds.brand_category_mapping" does not exist
LINE 1: INSERT INTO DDS.brand_category_mapping (brand, category_inde...
                    ^

[2024-12-05T20:54:06.363+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/llm_mapping.py", line 236, in execute_sql_wrapper
    return execute_sql(sql_code)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/llm_mapping.py", line 215, in execute_sql
    cursor.execute(sql_code)
psycopg2.errors.UndefinedTable: relation "dds.brand_category_mapping" does not exist
LINE 1: INSERT INTO DDS.brand_category_mapping (brand, category_inde...
                    ^

[2024-12-05T20:54:06.377+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=brand_category_mapping, task_id=execute_sql, run_id=manual__2024-12-05T20:53:43.542267+00:00, execution_date=20241205T205343, start_date=20241205T205405, end_date=20241205T205406
[2024-12-05T20:54:06.391+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T20:54:06.392+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 544 for task execute_sql (relation "dds.brand_category_mapping" does not exist
LINE 1: INSERT INTO DDS.brand_category_mapping (brand, category_inde...
                    ^
; 2451)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/llm_mapping.py", line 236, in execute_sql_wrapper
    return execute_sql(sql_code)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/llm_mapping.py", line 215, in execute_sql
    cursor.execute(sql_code)
psycopg2.errors.UndefinedTable: relation "dds.brand_category_mapping" does not exist
LINE 1: INSERT INTO DDS.brand_category_mapping (brand, category_inde...
                    ^

[2024-12-05T20:54:06.426+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-05T20:54:06.440+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T20:54:06.442+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
