[2024-12-05T17:29:53.067+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:29:53.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:29:53.072+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:29:53.072+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:29:53.642+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:29:53.638+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:29:53.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:29:53.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.592 seconds
[2024-12-05T17:30:23.824+0000] {processor.py:186} INFO - Started process (PID=91) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:30:23.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:30:23.827+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:30:23.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:30:24.226+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:30:24.221+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:30:24.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:30:24.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.422 seconds
[2024-12-05T17:30:55.101+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:30:55.103+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:30:55.108+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:30:55.108+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:30:55.611+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:30:55.608+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:30:55.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:30:55.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.532 seconds
[2024-12-05T17:31:26.057+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:31:26.057+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:31:26.059+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:31:26.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:31:26.400+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:31:26.396+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:31:26.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:31:26.408+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.357 seconds
[2024-12-05T17:31:56.793+0000] {processor.py:186} INFO - Started process (PID=150) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:31:56.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:31:56.796+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:31:56.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:31:57.051+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:31:57.048+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:31:57.053+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:31:57.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.275 seconds
[2024-12-05T17:32:27.449+0000] {processor.py:186} INFO - Started process (PID=169) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:32:27.450+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:32:27.451+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:32:27.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:32:27.702+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:32:27.693+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:32:27.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:32:27.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.281 seconds
[2024-12-05T17:32:57.864+0000] {processor.py:186} INFO - Started process (PID=188) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:32:57.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:32:57.868+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:32:57.867+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:32:58.136+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:32:58.133+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:32:58.138+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:32:58.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.291 seconds
[2024-12-05T17:33:28.438+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:33:28.439+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:33:28.441+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:33:28.441+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:33:28.698+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:33:28.695+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:33:28.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:33:28.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.274 seconds
[2024-12-05T17:33:59.044+0000] {processor.py:186} INFO - Started process (PID=226) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:33:59.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:33:59.047+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:33:59.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:33:59.304+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:33:59.301+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:33:59.305+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:33:59.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.275 seconds
[2024-12-05T17:34:29.620+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:34:29.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:34:29.622+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:34:29.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:34:29.908+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:34:29.899+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:34:29.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:34:29.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.319 seconds
[2024-12-05T17:34:59.980+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:34:59.981+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:34:59.983+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:34:59.983+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:35:00.241+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:35:00.235+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:35:00.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:35:00.251+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.276 seconds
[2024-12-05T17:35:30.481+0000] {processor.py:186} INFO - Started process (PID=283) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:35:30.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:35:30.484+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:35:30.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:35:30.753+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:35:30.749+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:35:30.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:35:30.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.287 seconds
[2024-12-05T17:36:01.004+0000] {processor.py:186} INFO - Started process (PID=302) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:36:01.004+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:36:01.006+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:36:01.006+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:36:01.255+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:36:01.253+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:36:01.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:36:01.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.267 seconds
[2024-12-05T17:36:31.513+0000] {processor.py:186} INFO - Started process (PID=321) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:36:31.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:36:31.516+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:36:31.515+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:36:31.780+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:36:31.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:36:31.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:36:31.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.283 seconds
[2024-12-05T17:37:02.550+0000] {processor.py:186} INFO - Started process (PID=340) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:37:02.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:37:02.556+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:37:02.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:37:02.883+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:37:02.878+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:37:02.885+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:37:02.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.354 seconds
[2024-12-05T17:37:33.233+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:37:33.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:37:33.238+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:37:33.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:37:33.518+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:37:33.515+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:37:33.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:37:33.530+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.304 seconds
[2024-12-05T17:38:03.944+0000] {processor.py:186} INFO - Started process (PID=378) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:38:03.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:38:03.947+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:38:03.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:38:04.193+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:38:04.190+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:38:04.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:38:04.202+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.270 seconds
[2024-12-05T17:38:34.505+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:38:34.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:38:34.508+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:38:34.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:38:34.767+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:38:34.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:38:34.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:38:34.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.279 seconds
[2024-12-05T17:39:05.096+0000] {processor.py:186} INFO - Started process (PID=416) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:39:05.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:39:05.100+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:39:05.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:39:05.427+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:39:05.424+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:39:05.429+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:39:05.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.348 seconds
[2024-12-05T17:39:36.346+0000] {processor.py:186} INFO - Started process (PID=435) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:39:36.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:39:36.349+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:39:36.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:39:36.615+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:39:36.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:39:36.616+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:39:36.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.284 seconds
[2024-12-05T17:40:06.828+0000] {processor.py:186} INFO - Started process (PID=454) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:40:06.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:40:06.832+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:40:06.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:40:07.098+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:40:07.094+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:40:07.099+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:40:07.109+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.286 seconds
[2024-12-05T17:40:37.308+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:40:37.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:40:37.311+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:40:37.310+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:40:37.570+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:40:37.566+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:40:37.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:40:37.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.277 seconds
[2024-12-05T17:41:07.790+0000] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:41:07.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:41:07.793+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:41:07.793+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:41:08.044+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:41:08.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:41:08.045+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:41:08.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.268 seconds
[2024-12-05T17:41:38.289+0000] {processor.py:186} INFO - Started process (PID=511) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:41:38.290+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:41:38.293+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:41:38.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:41:38.582+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:41:38.580+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:41:38.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:41:38.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.309 seconds
[2024-12-05T17:42:08.785+0000] {processor.py:186} INFO - Started process (PID=530) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:42:08.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:42:08.788+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:42:08.788+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:42:09.042+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:42:09.039+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:42:09.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:42:09.052+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.271 seconds
[2024-12-05T17:42:39.262+0000] {processor.py:186} INFO - Started process (PID=549) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:42:39.263+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:42:39.265+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:42:39.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:42:39.521+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:42:39.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:42:39.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:42:39.534+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.277 seconds
[2024-12-05T17:43:09.739+0000] {processor.py:186} INFO - Started process (PID=568) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:43:09.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:43:09.742+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:43:09.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:43:09.989+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:43:09.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:43:09.991+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:43:10.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.266 seconds
[2024-12-05T17:43:40.232+0000] {processor.py:186} INFO - Started process (PID=587) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:43:40.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:43:40.235+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:43:40.234+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:43:40.495+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:43:40.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:43:40.496+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:43:40.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.278 seconds
[2024-12-05T17:44:10.662+0000] {processor.py:186} INFO - Started process (PID=606) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:44:10.662+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:44:10.664+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:44:10.664+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:44:10.912+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:44:10.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:44:10.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:44:10.922+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.265 seconds
[2024-12-05T17:44:41.184+0000] {processor.py:186} INFO - Started process (PID=625) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:44:41.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:44:41.187+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:44:41.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:44:41.455+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:44:41.452+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:44:41.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:44:41.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.288 seconds
[2024-12-05T17:45:11.673+0000] {processor.py:186} INFO - Started process (PID=644) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:45:11.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:45:11.677+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:45:11.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:45:11.961+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:45:11.958+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:45:11.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:45:11.972+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.305 seconds
[2024-12-05T17:45:42.347+0000] {processor.py:186} INFO - Started process (PID=663) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:45:42.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:45:42.350+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:45:42.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:45:42.682+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:45:42.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:45:42.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:45:42.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.350 seconds
[2024-12-05T17:46:13.569+0000] {processor.py:186} INFO - Started process (PID=682) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:46:13.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:46:13.572+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:46:13.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:46:13.828+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:46:13.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:46:13.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:46:13.839+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.274 seconds
[2024-12-05T17:46:44.145+0000] {processor.py:186} INFO - Started process (PID=701) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:46:44.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:46:44.148+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:46:44.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:46:44.385+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:46:44.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:46:44.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:46:44.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.255 seconds
[2024-12-05T17:47:14.860+0000] {processor.py:186} INFO - Started process (PID=720) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:47:14.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:47:14.863+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:47:14.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:47:15.139+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:47:15.135+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:47:15.140+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:47:15.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.294 seconds
[2024-12-05T17:47:45.394+0000] {processor.py:186} INFO - Started process (PID=739) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:47:45.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:47:45.398+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:47:45.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:47:45.658+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:47:45.655+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:47:45.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:47:45.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.281 seconds
[2024-12-05T17:48:16.032+0000] {processor.py:186} INFO - Started process (PID=758) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:48:16.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:48:16.035+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:48:16.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:48:16.288+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:48:16.285+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:48:16.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:48:16.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.270 seconds
[2024-12-05T17:48:46.569+0000] {processor.py:186} INFO - Started process (PID=777) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:48:46.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:48:46.572+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:48:46.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:48:46.838+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:48:46.835+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:48:46.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:48:46.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.286 seconds
[2024-12-05T17:49:17.350+0000] {processor.py:186} INFO - Started process (PID=796) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:49:17.351+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:49:17.353+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:49:17.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:49:17.618+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:49:17.614+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:49:17.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:49:17.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.285 seconds
[2024-12-05T17:49:47.912+0000] {processor.py:186} INFO - Started process (PID=815) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:49:47.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:49:47.915+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:49:47.915+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:49:48.181+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:49:48.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:49:48.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:49:48.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.285 seconds
[2024-12-05T17:50:18.437+0000] {processor.py:186} INFO - Started process (PID=834) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:50:18.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:50:18.440+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:50:18.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:50:18.715+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:50:18.711+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:50:18.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:50:18.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.297 seconds
[2024-12-05T17:50:49.056+0000] {processor.py:186} INFO - Started process (PID=853) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:50:49.057+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:50:49.059+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:50:49.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:50:49.315+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:50:49.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:50:49.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:50:49.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.276 seconds
[2024-12-05T17:51:19.464+0000] {processor.py:186} INFO - Started process (PID=872) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:51:19.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:51:19.467+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:51:19.466+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:51:19.738+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:51:19.732+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:51:19.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:51:19.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.298 seconds
[2024-12-05T17:51:50.019+0000] {processor.py:186} INFO - Started process (PID=890) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:51:50.019+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:51:50.021+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:51:50.021+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:51:50.383+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:51:50.381+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:51:50.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:51:50.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.379 seconds
[2024-12-05T17:52:20.855+0000] {processor.py:186} INFO - Started process (PID=910) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:52:20.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:52:20.861+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:52:20.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:52:21.304+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:52:21.301+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:52:21.305+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:52:21.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.470 seconds
[2024-12-05T17:52:51.553+0000] {processor.py:186} INFO - Started process (PID=929) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:52:51.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:52:51.556+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:52:51.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:52:51.910+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:52:51.907+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:52:51.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:52:51.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.370 seconds
[2024-12-05T17:53:22.447+0000] {processor.py:186} INFO - Started process (PID=948) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:53:22.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:53:22.452+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:53:22.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:53:22.940+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:53:22.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:53:22.943+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:53:22.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.522 seconds
[2024-12-05T17:53:53.160+0000] {processor.py:186} INFO - Started process (PID=972) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:53:53.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:53:53.163+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:53:53.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:53:53.514+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:53:53.511+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:53:53.515+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:53:53.524+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.368 seconds
[2024-12-05T17:54:23.930+0000] {processor.py:186} INFO - Started process (PID=992) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:54:23.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:54:23.933+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:54:23.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:54:24.293+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:54:24.290+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:54:24.294+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:54:24.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.381 seconds
[2024-12-05T17:54:54.792+0000] {processor.py:186} INFO - Started process (PID=1011) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:54:54.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:54:54.795+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:54:54.794+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:54:55.179+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:54:55.176+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:54:55.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:54:55.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.402 seconds
[2024-12-05T17:55:25.402+0000] {processor.py:186} INFO - Started process (PID=1030) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:55:25.403+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:55:25.405+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:55:25.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:55:25.796+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:55:25.793+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:55:25.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:55:25.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.409 seconds
[2024-12-05T17:55:55.960+0000] {processor.py:186} INFO - Started process (PID=1049) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:55:55.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:55:55.963+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:55:55.963+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:55:56.309+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:55:56.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:55:56.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:55:56.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.363 seconds
[2024-12-05T17:56:26.784+0000] {processor.py:186} INFO - Started process (PID=1068) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:56:26.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:56:26.787+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:56:26.787+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:56:27.205+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:56:27.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:56:27.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:56:27.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.436 seconds
[2024-12-05T17:56:57.290+0000] {processor.py:186} INFO - Started process (PID=1087) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:56:57.290+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:56:57.293+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:56:57.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:56:57.683+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:56:57.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:56:57.684+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:56:57.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.407 seconds
[2024-12-05T17:57:28.272+0000] {processor.py:186} INFO - Started process (PID=1106) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:57:28.273+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:57:28.275+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:57:28.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:57:28.633+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:57:28.630+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:57:28.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:57:28.642+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.375 seconds
[2024-12-05T17:57:58.896+0000] {processor.py:186} INFO - Started process (PID=1125) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:57:58.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:57:58.899+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:57:58.899+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:57:59.300+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:57:59.297+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:57:59.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:57:59.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.419 seconds
[2024-12-05T17:58:29.485+0000] {processor.py:186} INFO - Started process (PID=1144) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:58:29.486+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:58:29.488+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:58:29.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:58:29.879+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:58:29.877+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:58:29.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:58:29.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.409 seconds
[2024-12-05T17:59:00.106+0000] {processor.py:186} INFO - Started process (PID=1163) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:59:00.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:59:00.109+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:59:00.108+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:59:00.494+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:59:00.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:59:00.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:59:00.502+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.401 seconds
[2024-12-05T17:59:30.634+0000] {processor.py:186} INFO - Started process (PID=1182) to work on /opt/airflow/dags/weather.py
[2024-12-05T17:59:30.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T17:59:30.638+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:59:30.637+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T17:59:31.015+0000] {logging_mixin.py:190} INFO - [2024-12-05T17:59:31.012+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T17:59:31.016+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T17:59:31.024+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.396 seconds
[2024-12-05T18:00:01.290+0000] {processor.py:186} INFO - Started process (PID=1201) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:00:01.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:00:01.293+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:00:01.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:00:01.754+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:00:01.744+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:00:01.757+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:00:01.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.491 seconds
[2024-12-05T18:00:31.903+0000] {processor.py:186} INFO - Started process (PID=1220) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:00:31.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:00:31.906+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:00:31.905+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:00:32.286+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:00:32.283+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:00:32.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:00:32.295+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.397 seconds
[2024-12-05T18:01:02.462+0000] {processor.py:186} INFO - Started process (PID=1239) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:01:02.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:01:02.464+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:01:02.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:01:02.843+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:01:02.840+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:01:02.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:01:02.853+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.396 seconds
[2024-12-05T18:01:32.998+0000] {processor.py:186} INFO - Started process (PID=1258) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:01:32.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:01:33.001+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:01:33.000+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:01:33.377+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:01:33.372+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:01:33.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:01:33.386+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.394 seconds
[2024-12-05T18:02:03.616+0000] {processor.py:186} INFO - Started process (PID=1277) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:02:03.617+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:02:03.619+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:02:03.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:02:04.005+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:02:04.002+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:02:04.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:02:04.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.403 seconds
[2024-12-05T18:02:34.105+0000] {processor.py:186} INFO - Started process (PID=1296) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:02:34.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:02:34.108+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:02:34.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:02:34.472+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:02:34.469+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:02:34.472+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:02:34.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.381 seconds
[2024-12-05T18:03:04.688+0000] {processor.py:186} INFO - Started process (PID=1315) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:03:04.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:03:04.691+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:03:04.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:03:05.048+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:03:05.044+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:03:05.049+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:03:05.058+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.375 seconds
[2024-12-05T18:03:35.337+0000] {processor.py:186} INFO - Started process (PID=1334) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:03:35.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:03:35.340+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:03:35.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:03:35.717+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:03:35.714+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:03:35.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:03:35.727+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.395 seconds
[2024-12-05T18:04:05.975+0000] {processor.py:186} INFO - Started process (PID=1353) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:04:05.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:04:05.978+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:04:05.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:04:06.330+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:04:06.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:04:06.330+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:04:06.338+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.368 seconds
[2024-12-05T18:04:36.477+0000] {processor.py:186} INFO - Started process (PID=1372) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:04:36.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:04:36.480+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:04:36.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:04:36.870+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:04:36.867+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:04:36.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:04:36.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.408 seconds
[2024-12-05T18:05:07.141+0000] {processor.py:186} INFO - Started process (PID=1391) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:05:07.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:05:07.144+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:05:07.143+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:05:07.514+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:05:07.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:05:07.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:05:07.544+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.409 seconds
[2024-12-05T18:05:37.815+0000] {processor.py:186} INFO - Started process (PID=1410) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:05:37.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:05:37.818+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:05:37.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:05:38.218+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:05:38.215+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:05:38.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:05:38.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.417 seconds
[2024-12-05T18:06:08.381+0000] {processor.py:186} INFO - Started process (PID=1429) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:06:08.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:06:08.385+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:06:08.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:06:08.741+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:06:08.738+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:06:08.742+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:06:08.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.374 seconds
[2024-12-05T18:06:38.910+0000] {processor.py:186} INFO - Started process (PID=1448) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:06:38.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:06:38.914+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:06:38.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:06:39.299+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:06:39.295+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:06:39.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:06:39.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.406 seconds
[2024-12-05T18:07:09.532+0000] {processor.py:186} INFO - Started process (PID=1467) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:07:09.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:07:09.535+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:07:09.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:07:09.928+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:07:09.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:07:09.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:07:09.938+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.412 seconds
[2024-12-05T18:07:40.279+0000] {processor.py:186} INFO - Started process (PID=1486) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:07:40.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:07:40.282+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:07:40.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:07:40.745+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:07:40.734+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:07:40.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:07:40.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.491 seconds
[2024-12-05T18:08:10.910+0000] {processor.py:186} INFO - Started process (PID=1505) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:08:10.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:08:10.913+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:08:10.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:08:11.301+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:08:11.297+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:08:11.302+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:08:11.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.407 seconds
[2024-12-05T18:08:41.525+0000] {processor.py:186} INFO - Started process (PID=1524) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:08:41.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:08:41.527+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:08:41.527+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:08:41.888+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:08:41.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:08:41.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:08:41.897+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.378 seconds
[2024-12-05T18:09:12.096+0000] {processor.py:186} INFO - Started process (PID=1543) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:09:12.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:09:12.099+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:09:12.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:09:12.470+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:09:12.467+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:09:12.471+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:09:12.483+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.392 seconds
[2024-12-05T18:09:42.574+0000] {processor.py:186} INFO - Started process (PID=1562) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:09:42.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:09:42.577+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:09:42.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:09:42.938+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:09:42.935+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:09:42.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:09:42.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.379 seconds
[2024-12-05T18:10:13.184+0000] {processor.py:186} INFO - Started process (PID=1581) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:10:13.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:10:13.187+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:10:13.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:10:13.547+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:10:13.543+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:10:13.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:10:13.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.379 seconds
[2024-12-05T18:10:43.683+0000] {processor.py:186} INFO - Started process (PID=1600) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:10:43.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:10:43.686+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:10:43.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:10:44.059+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:10:44.056+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:10:44.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:10:44.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.391 seconds
[2024-12-05T18:11:14.414+0000] {processor.py:186} INFO - Started process (PID=1619) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:11:14.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:11:14.418+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:11:14.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:11:14.799+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:11:14.797+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:11:14.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:11:14.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.400 seconds
[2024-12-05T18:11:44.903+0000] {processor.py:186} INFO - Started process (PID=1638) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:11:44.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:11:44.906+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:11:44.906+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:11:45.153+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:11:45.150+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:11:45.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:11:45.163+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.265 seconds
[2024-12-05T18:12:15.459+0000] {processor.py:186} INFO - Started process (PID=1657) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:12:15.460+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:12:15.462+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:12:15.462+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:12:15.718+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:12:15.715+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:12:15.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:12:15.727+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.273 seconds
[2024-12-05T18:12:46.002+0000] {processor.py:186} INFO - Started process (PID=1676) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:12:46.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:12:46.005+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:12:46.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:12:46.260+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:12:46.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:12:46.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:12:46.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.273 seconds
[2024-12-05T18:13:16.515+0000] {processor.py:186} INFO - Started process (PID=1695) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:13:16.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:13:16.518+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:13:16.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:13:16.747+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:13:16.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:13:16.748+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:13:16.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.247 seconds
[2024-12-05T18:13:46.958+0000] {processor.py:186} INFO - Started process (PID=1714) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:13:46.959+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:13:46.961+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:13:46.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:13:47.211+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:13:47.206+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:13:47.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:13:47.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.267 seconds
[2024-12-05T18:14:17.586+0000] {processor.py:186} INFO - Started process (PID=1733) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:14:17.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:14:17.592+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:14:17.591+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:14:17.880+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:14:17.876+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:14:17.881+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:14:17.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.317 seconds
[2024-12-05T18:14:48.087+0000] {processor.py:186} INFO - Started process (PID=1752) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:14:48.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:14:48.090+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:14:48.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:14:48.346+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:14:48.343+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:14:48.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:14:48.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.275 seconds
[2024-12-05T18:15:18.393+0000] {processor.py:186} INFO - Started process (PID=1771) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:15:18.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:15:18.396+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:15:18.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:15:18.633+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:15:18.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:15:18.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:15:18.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.254 seconds
[2024-12-05T18:15:48.883+0000] {processor.py:186} INFO - Started process (PID=1789) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:15:48.883+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:15:48.885+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:15:48.885+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:15:49.149+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:15:49.146+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:15:49.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:15:49.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.282 seconds
[2024-12-05T18:16:19.719+0000] {processor.py:186} INFO - Started process (PID=1809) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:16:19.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:16:19.722+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:16:19.721+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:16:19.998+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:16:19.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:16:20.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:16:20.010+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.297 seconds
[2024-12-05T18:16:50.306+0000] {processor.py:186} INFO - Started process (PID=1828) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:16:50.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:16:50.310+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:16:50.309+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:16:50.553+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:16:50.550+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:16:50.554+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:16:50.563+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.263 seconds
[2024-12-05T18:17:20.891+0000] {processor.py:186} INFO - Started process (PID=1847) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:17:20.892+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:17:20.894+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:17:20.894+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:17:21.150+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:17:21.146+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:17:21.151+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:17:21.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.275 seconds
[2024-12-05T18:17:51.469+0000] {processor.py:186} INFO - Started process (PID=1866) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:17:51.470+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:17:51.472+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:17:51.472+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:17:51.708+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:17:51.705+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:17:51.709+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:17:51.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.253 seconds
[2024-12-05T18:18:21.916+0000] {processor.py:186} INFO - Started process (PID=1885) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:18:21.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:18:21.919+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:18:21.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:18:22.152+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:18:22.150+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:18:22.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:18:22.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.250 seconds
[2024-12-05T18:18:52.381+0000] {processor.py:186} INFO - Started process (PID=1904) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:18:52.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:18:52.384+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:18:52.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:18:52.627+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:18:52.623+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:18:52.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:18:52.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.261 seconds
[2024-12-05T18:19:22.818+0000] {processor.py:186} INFO - Started process (PID=1923) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:19:22.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:19:22.821+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:19:22.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:19:23.071+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:19:23.068+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:19:23.072+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:19:23.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.267 seconds
[2024-12-05T18:19:53.441+0000] {processor.py:186} INFO - Started process (PID=1942) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:19:53.442+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:19:53.444+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:19:53.443+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:19:53.676+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:19:53.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:19:53.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:19:53.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.248 seconds
[2024-12-05T18:20:23.858+0000] {processor.py:186} INFO - Started process (PID=1961) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:20:23.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:20:23.861+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:20:23.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:20:24.083+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:20:24.080+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:20:24.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:20:24.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.239 seconds
[2024-12-05T18:20:54.394+0000] {processor.py:186} INFO - Started process (PID=1980) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:20:54.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:20:54.396+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:20:54.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:20:54.725+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:20:54.722+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:20:54.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:20:54.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.347 seconds
[2024-12-05T18:21:24.839+0000] {processor.py:186} INFO - Started process (PID=2005) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:21:24.840+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:21:24.841+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:21:24.841+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:21:25.075+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:21:25.071+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:21:25.076+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:21:25.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.251 seconds
[2024-12-05T18:21:55.298+0000] {processor.py:186} INFO - Started process (PID=2023) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:21:55.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:21:55.301+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:21:55.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:21:55.539+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:21:55.536+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:21:55.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:21:55.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.255 seconds
[2024-12-05T18:22:25.771+0000] {processor.py:186} INFO - Started process (PID=2042) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:22:25.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:22:25.773+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:22:25.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:22:26.015+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:22:26.011+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:22:26.016+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:22:26.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.259 seconds
[2024-12-05T18:22:56.321+0000] {processor.py:186} INFO - Started process (PID=2061) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:22:56.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:22:56.324+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:22:56.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:22:56.590+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:22:56.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:22:56.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:22:56.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.285 seconds
[2024-12-05T18:23:26.836+0000] {processor.py:186} INFO - Started process (PID=2080) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:23:26.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:23:26.840+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:23:26.839+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:23:27.115+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:23:27.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:23:27.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:23:27.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.296 seconds
[2024-12-05T18:23:57.325+0000] {processor.py:186} INFO - Started process (PID=2099) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:23:57.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:23:57.328+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:23:57.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:23:57.609+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:23:57.605+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:23:57.610+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:23:57.618+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.299 seconds
[2024-12-05T18:24:27.876+0000] {processor.py:186} INFO - Started process (PID=2118) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:24:27.876+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:24:27.879+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:24:27.878+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:24:28.119+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:24:28.116+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:24:28.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:24:28.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.258 seconds
[2024-12-05T18:24:58.187+0000] {processor.py:186} INFO - Started process (PID=2137) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:24:58.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:24:58.189+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:24:58.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:24:58.425+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:24:58.421+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:24:58.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:24:58.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.254 seconds
[2024-12-05T18:25:28.717+0000] {processor.py:186} INFO - Started process (PID=2156) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:25:28.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:25:28.719+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:25:28.719+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:25:28.955+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:25:28.952+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:25:28.957+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:25:28.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.254 seconds
[2024-12-05T18:25:59.165+0000] {processor.py:186} INFO - Started process (PID=2175) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:25:59.166+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:25:59.168+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:25:59.168+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:25:59.406+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:25:59.403+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:25:59.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:25:59.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.256 seconds
[2024-12-05T18:26:29.669+0000] {processor.py:186} INFO - Started process (PID=2194) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:26:29.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:26:29.672+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:26:29.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:26:29.898+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:26:29.894+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:26:29.899+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:26:29.906+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.242 seconds
[2024-12-05T18:27:00.087+0000] {processor.py:186} INFO - Started process (PID=2213) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:27:00.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:27:00.090+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:27:00.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:27:00.320+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:27:00.316+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:27:00.321+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:27:00.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.248 seconds
[2024-12-05T18:27:30.876+0000] {processor.py:186} INFO - Started process (PID=2232) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:27:30.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:27:30.879+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:27:30.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:27:31.115+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:27:31.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:27:31.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:27:31.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.258 seconds
[2024-12-05T18:28:01.355+0000] {processor.py:186} INFO - Started process (PID=2251) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:28:01.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:28:01.358+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:28:01.357+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:28:01.599+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:28:01.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:28:01.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:28:01.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.259 seconds
[2024-12-05T18:28:32.076+0000] {processor.py:186} INFO - Started process (PID=2270) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:28:32.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:28:32.082+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:28:32.082+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:28:32.403+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:28:32.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:28:32.406+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:28:32.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.358 seconds
[2024-12-05T18:29:02.557+0000] {processor.py:186} INFO - Started process (PID=2289) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:29:02.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:29:02.560+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:29:02.560+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:29:02.804+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:29:02.800+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:29:02.805+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:29:02.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.260 seconds
[2024-12-05T18:29:33.008+0000] {processor.py:186} INFO - Started process (PID=2308) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:29:33.009+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:29:33.011+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:29:33.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:29:33.246+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:29:33.242+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:29:33.246+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:29:33.255+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.252 seconds
[2024-12-05T18:30:03.537+0000] {processor.py:186} INFO - Started process (PID=2327) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:30:03.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:30:03.540+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:30:03.539+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:30:03.772+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:30:03.770+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:30:03.773+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:30:03.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.249 seconds
[2024-12-05T18:30:33.975+0000] {processor.py:186} INFO - Started process (PID=2346) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:30:33.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:30:33.978+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:30:33.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:30:34.213+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:30:34.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:30:34.214+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:30:34.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.253 seconds
[2024-12-05T18:31:04.606+0000] {processor.py:186} INFO - Started process (PID=2365) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:31:04.608+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:31:04.611+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:31:04.610+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:31:04.894+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:31:04.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:31:04.895+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:31:04.905+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.305 seconds
[2024-12-05T18:31:35.774+0000] {processor.py:186} INFO - Started process (PID=2384) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:31:35.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:31:35.777+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:31:35.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:31:36.028+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:31:36.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:31:36.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:31:36.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.268 seconds
[2024-12-05T18:32:06.232+0000] {processor.py:186} INFO - Started process (PID=2403) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:32:06.233+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:32:06.235+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:32:06.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:32:06.467+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:32:06.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:32:06.468+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:32:06.476+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.249 seconds
[2024-12-05T18:32:36.629+0000] {processor.py:186} INFO - Started process (PID=2421) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:32:36.630+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:32:36.632+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:32:36.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:32:36.880+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:32:36.876+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:32:36.881+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:32:36.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.266 seconds
[2024-12-05T18:33:07.062+0000] {processor.py:186} INFO - Started process (PID=2440) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:33:07.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:33:07.065+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:33:07.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:33:07.300+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:33:07.297+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:33:07.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:33:07.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.253 seconds
[2024-12-05T18:34:19.196+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:34:19.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:34:19.200+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:34:19.199+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:34:19.601+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:34:19.598+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:34:19.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:34:19.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.419 seconds
[2024-12-05T18:34:50.496+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:34:50.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:34:50.499+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:34:50.499+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:34:50.838+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:34:50.835+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:34:50.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:34:50.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.357 seconds
[2024-12-05T18:35:22.133+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:35:22.134+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:35:22.135+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:35:22.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:35:22.453+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:35:22.450+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:35:22.454+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:35:22.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.333 seconds
[2024-12-05T18:35:52.887+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:35:52.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:35:52.889+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:35:52.889+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:35:53.204+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:35:53.200+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:35:53.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:35:53.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.331 seconds
[2024-12-05T18:36:23.868+0000] {processor.py:186} INFO - Started process (PID=162) to work on /opt/airflow/dags/weather.py
[2024-12-05T18:36:23.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-05T18:36:23.871+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:36:23.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-05T18:36:24.129+0000] {logging_mixin.py:190} INFO - [2024-12-05T18:36:24.124+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-05T18:36:24.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-05T18:36:24.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.282 seconds
