[2024-12-01T00:01:08.333+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:01:08.335+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:01:08.337+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:01:08.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:01:08.875+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:01:08.867+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:01:08.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:01:08.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.592 seconds
[2024-12-01T00:01:39.121+0000] {processor.py:186} INFO - Started process (PID=91) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:01:39.123+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:01:39.127+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:01:39.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:01:39.572+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:01:39.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:01:39.574+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:01:39.585+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.476 seconds
[2024-12-01T00:02:10.191+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:02:10.192+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:02:10.194+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:02:10.194+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:02:10.576+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:02:10.573+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:02:10.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:02:10.585+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.399 seconds
[2024-12-01T00:03:01.108+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:03:01.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:03:01.112+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:03:01.111+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:03:01.500+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:03:01.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:03:01.501+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:03:01.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.406 seconds
[2024-12-01T00:03:31.963+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:03:31.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:03:31.966+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:03:31.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:03:32.311+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:03:32.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:03:32.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:03:32.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.362 seconds
[2024-12-01T00:04:02.958+0000] {processor.py:186} INFO - Started process (PID=118) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:04:02.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:04:02.960+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:04:02.960+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:04:03.494+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:04:03.491+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:04:03.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:04:03.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.552 seconds
[2024-12-01T00:04:34.204+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:04:34.205+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:04:34.207+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:04:34.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:04:34.654+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:04:34.651+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:04:34.655+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:04:34.665+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.467 seconds
[2024-12-01T00:06:02.436+0000] {processor.py:186} INFO - Started process (PID=66) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:06:02.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:06:02.439+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:06:02.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:06:02.890+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:06:02.888+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:06:02.891+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:06:02.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.468 seconds
[2024-12-01T00:06:33.486+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:06:33.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:06:33.490+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:06:33.489+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:06:33.993+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:06:33.990+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:06:33.993+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:06:34.001+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.525 seconds
[2024-12-01T00:07:04.387+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:07:04.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:07:04.390+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:07:04.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:07:04.745+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:07:04.743+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:07:04.746+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:07:04.754+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.371 seconds
[2024-12-01T00:07:35.275+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:07:35.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:07:35.278+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:07:35.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:07:35.710+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:07:35.706+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:07:35.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:07:35.721+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.451 seconds
[2024-12-01T00:08:06.194+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:08:06.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:08:06.197+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:08:06.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:08:06.442+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:08:06.439+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:08:06.444+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:08:06.454+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.266 seconds
[2024-12-01T00:08:53.268+0000] {processor.py:186} INFO - Started process (PID=67) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:08:53.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:08:53.270+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:08:53.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:08:53.615+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:08:53.613+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:08:53.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:08:53.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.361 seconds
[2024-12-01T00:09:24.290+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:09:24.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:09:24.292+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:09:24.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:09:24.644+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:09:24.642+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:09:24.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:09:24.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.368 seconds
[2024-12-01T00:09:56.023+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:09:56.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:09:56.025+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:09:56.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:09:56.391+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:09:56.388+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:09:56.392+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:09:56.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.382 seconds
[2024-12-01T00:10:28.028+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:10:28.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:10:28.034+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:10:28.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:10:28.430+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:10:28.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:10:28.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:10:28.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.422 seconds
[2024-12-01T00:10:59.010+0000] {processor.py:186} INFO - Started process (PID=153) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:10:59.011+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:10:59.014+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:10:59.013+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:10:59.341+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:10:59.332+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:10:59.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:10:59.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.364 seconds
[2024-12-01T00:11:29.505+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:11:29.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:11:29.509+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:11:29.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:11:29.761+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:11:29.758+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:11:29.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:11:29.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.279 seconds
[2024-12-01T00:12:00.023+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:12:00.024+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:12:00.026+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:12:00.026+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:12:00.336+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:12:00.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:12:00.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:12:00.360+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.342 seconds
[2024-12-01T00:12:30.702+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:12:30.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:12:30.705+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:12:30.705+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:12:31.048+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:12:31.044+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:12:31.050+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:12:31.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.363 seconds
[2024-12-01T00:13:01.205+0000] {processor.py:186} INFO - Started process (PID=233) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:13:01.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:13:01.209+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:13:01.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:13:01.548+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:13:01.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:13:01.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:13:01.559+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.360 seconds
[2024-12-01T00:13:31.728+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:13:31.729+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:13:31.731+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:13:31.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:13:32.065+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:13:32.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:13:32.066+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:13:32.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.353 seconds
[2024-12-01T00:14:02.400+0000] {processor.py:186} INFO - Started process (PID=273) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:14:02.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:14:02.403+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:14:02.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:14:02.666+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:14:02.663+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:14:02.667+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:14:02.675+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.280 seconds
[2024-12-01T00:14:33.168+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:14:33.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:14:33.171+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:14:33.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:14:33.415+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:14:33.410+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:14:33.416+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:14:33.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.262 seconds
[2024-12-01T00:15:03.873+0000] {processor.py:186} INFO - Started process (PID=313) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:15:03.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:15:03.876+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:15:03.875+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:15:04.136+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:15:04.132+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:15:04.137+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:15:04.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.279 seconds
[2024-12-01T00:15:34.383+0000] {processor.py:186} INFO - Started process (PID=333) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:15:34.383+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:15:34.385+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:15:34.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:15:34.644+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:15:34.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:15:34.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:15:34.654+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.276 seconds
[2024-12-01T00:16:04.867+0000] {processor.py:186} INFO - Started process (PID=352) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:16:04.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:16:04.870+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:16:04.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:16:05.090+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:16:05.087+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:16:05.091+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:16:05.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.236 seconds
[2024-12-01T00:16:35.681+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:16:35.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:16:35.688+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:16:35.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:16:36.003+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:16:35.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:16:36.004+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:16:36.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.346 seconds
[2024-12-01T00:17:06.620+0000] {processor.py:186} INFO - Started process (PID=393) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:17:06.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:17:06.623+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:17:06.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:17:07.075+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:17:07.070+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:17:07.077+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:17:07.089+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.472 seconds
[2024-12-01T00:17:37.537+0000] {processor.py:186} INFO - Started process (PID=412) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:17:37.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:17:37.541+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:17:37.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:17:37.857+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:17:37.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:17:37.858+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:17:37.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.338 seconds
[2024-12-01T00:18:08.137+0000] {processor.py:186} INFO - Started process (PID=433) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:18:08.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:18:08.140+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:18:08.140+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:18:08.390+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:18:08.387+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:18:08.391+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:18:08.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.268 seconds
[2024-12-01T00:18:38.929+0000] {processor.py:186} INFO - Started process (PID=453) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:18:38.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:18:38.932+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:18:38.931+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:18:39.271+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:18:39.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:18:39.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:18:39.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.359 seconds
[2024-12-01T00:19:09.682+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:19:09.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:19:09.685+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:19:09.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:19:10.011+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:19:10.003+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:19:10.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:19:10.027+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.351 seconds
[2024-12-01T00:19:40.682+0000] {processor.py:186} INFO - Started process (PID=493) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:19:40.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:19:40.685+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:19:40.685+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:19:40.951+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:19:40.948+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:19:40.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:19:40.962+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.286 seconds
[2024-12-01T00:20:11.162+0000] {processor.py:186} INFO - Started process (PID=513) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:20:11.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:20:11.166+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:20:11.165+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:20:11.430+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:20:11.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:20:11.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:20:11.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.284 seconds
[2024-12-01T00:20:41.826+0000] {processor.py:186} INFO - Started process (PID=533) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:20:41.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:20:41.834+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:20:41.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:20:42.162+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:20:42.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:20:42.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:20:42.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.362 seconds
[2024-12-01T00:21:12.512+0000] {processor.py:186} INFO - Started process (PID=553) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:21:12.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:21:12.516+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:21:12.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:21:12.811+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:21:12.806+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:21:12.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:21:12.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.316 seconds
[2024-12-01T00:21:43.613+0000] {processor.py:186} INFO - Started process (PID=573) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:21:43.614+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:21:43.617+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:21:43.617+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:21:43.917+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:21:43.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:21:43.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:21:43.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.336 seconds
[2024-12-01T00:22:14.070+0000] {processor.py:186} INFO - Started process (PID=593) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:22:14.071+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:22:14.075+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:22:14.074+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:22:14.418+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:22:14.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:22:14.421+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:22:14.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.378 seconds
[2024-12-01T00:22:44.756+0000] {processor.py:186} INFO - Started process (PID=613) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:22:44.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:22:44.761+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:22:44.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:22:45.121+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:22:45.118+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:22:45.122+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:22:45.130+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.379 seconds
[2024-12-01T00:23:15.701+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:23:15.702+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:23:15.705+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:23:15.705+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:23:16.035+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:23:16.031+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:23:16.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:23:16.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.355 seconds
[2024-12-01T00:23:46.401+0000] {processor.py:186} INFO - Started process (PID=653) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:23:46.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:23:46.405+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:23:46.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:23:46.699+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:23:46.695+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:23:46.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:23:46.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.316 seconds
[2024-12-01T00:24:17.272+0000] {processor.py:186} INFO - Started process (PID=674) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:24:17.273+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:24:17.276+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:24:17.276+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:24:17.616+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:24:17.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:24:17.618+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:24:17.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.365 seconds
[2024-12-01T00:24:47.955+0000] {processor.py:186} INFO - Started process (PID=694) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:24:47.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:24:47.959+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:24:47.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:24:48.258+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:24:48.254+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:24:48.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:24:48.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.322 seconds
[2024-12-01T00:25:19.451+0000] {processor.py:186} INFO - Started process (PID=714) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:25:19.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:25:19.458+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:25:19.457+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:25:19.880+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:25:19.871+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:25:19.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:25:19.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.453 seconds
[2024-12-01T00:25:50.239+0000] {processor.py:186} INFO - Started process (PID=734) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:25:50.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:25:50.243+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:25:50.243+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:25:50.551+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:25:50.546+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:25:50.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:25:50.564+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.331 seconds
[2024-12-01T00:26:20.840+0000] {processor.py:186} INFO - Started process (PID=754) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:26:20.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:26:20.844+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:26:20.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:26:21.135+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:26:21.131+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:26:21.136+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:26:21.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.315 seconds
[2024-12-01T00:26:52.126+0000] {processor.py:186} INFO - Started process (PID=774) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:26:52.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:26:52.131+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:26:52.130+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:26:52.434+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:26:52.430+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:26:52.436+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:26:52.448+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.329 seconds
[2024-12-01T00:27:23.085+0000] {processor.py:186} INFO - Started process (PID=794) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:27:23.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:27:23.088+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:27:23.088+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:27:23.409+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:27:23.403+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:27:23.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:27:23.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.345 seconds
[2024-12-01T00:27:53.630+0000] {processor.py:186} INFO - Started process (PID=813) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:27:53.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:27:53.633+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:27:53.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:27:53.928+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:27:53.924+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:27:53.930+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:27:53.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.318 seconds
[2024-12-01T00:28:24.113+0000] {processor.py:186} INFO - Started process (PID=832) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:28:24.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:28:24.117+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:28:24.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:28:24.419+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:28:24.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:28:24.420+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:28:24.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.325 seconds
[2024-12-01T00:28:54.660+0000] {processor.py:186} INFO - Started process (PID=852) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:28:54.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:28:54.664+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:28:54.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:28:54.966+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:28:54.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:28:54.968+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:28:54.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.324 seconds
[2024-12-01T00:29:25.222+0000] {processor.py:186} INFO - Started process (PID=871) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:29:25.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:29:25.226+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:29:25.225+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:29:25.549+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:29:25.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:29:25.551+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:29:25.563+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.347 seconds
[2024-12-01T00:29:55.796+0000] {processor.py:186} INFO - Started process (PID=891) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:29:55.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:29:55.800+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:29:55.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:29:56.106+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:29:56.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:29:56.108+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:29:56.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.333 seconds
[2024-12-01T00:30:26.346+0000] {processor.py:186} INFO - Started process (PID=911) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:30:26.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:30:26.350+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:30:26.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:30:26.654+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:30:26.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:30:26.655+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:30:26.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.326 seconds
[2024-12-01T00:30:56.999+0000] {processor.py:186} INFO - Started process (PID=931) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:30:57.000+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:30:57.003+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:30:57.003+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:30:57.313+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:30:57.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:30:57.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:30:57.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.333 seconds
[2024-12-01T00:31:27.581+0000] {processor.py:186} INFO - Started process (PID=951) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:31:27.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:31:27.584+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:31:27.584+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:31:27.909+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:31:27.904+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:31:27.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:31:27.924+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.348 seconds
[2024-12-01T00:31:58.511+0000] {processor.py:186} INFO - Started process (PID=977) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:31:58.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:31:58.515+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:31:58.514+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:31:58.902+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:31:58.897+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:31:58.904+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:31:58.915+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.409 seconds
[2024-12-01T00:32:29.429+0000] {processor.py:186} INFO - Started process (PID=997) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:32:29.430+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:32:29.432+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:32:29.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:32:29.740+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:32:29.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:32:29.742+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:32:29.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.331 seconds
[2024-12-01T00:33:00.533+0000] {processor.py:186} INFO - Started process (PID=1017) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:33:00.534+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:33:00.536+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:33:00.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:33:00.854+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:33:00.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:33:00.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:33:00.868+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.341 seconds
[2024-12-01T00:33:31.467+0000] {processor.py:186} INFO - Started process (PID=1037) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:33:31.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:33:31.471+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:33:31.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:33:31.782+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:33:31.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:33:31.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:33:31.797+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.337 seconds
[2024-12-01T00:34:02.170+0000] {processor.py:186} INFO - Started process (PID=1057) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:34:02.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:34:02.174+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:34:02.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:34:02.485+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:34:02.479+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:34:02.486+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:34:02.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.335 seconds
[2024-12-01T00:34:32.849+0000] {processor.py:186} INFO - Started process (PID=1077) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:34:32.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:34:32.853+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:34:32.852+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:34:33.323+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:34:33.318+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:34:33.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:34:33.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.493 seconds
[2024-12-01T00:35:03.487+0000] {processor.py:186} INFO - Started process (PID=1097) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:35:03.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:35:03.492+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:35:03.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:35:04.003+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:35:03.998+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:35:04.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:35:04.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.537 seconds
[2024-12-01T00:35:34.180+0000] {processor.py:186} INFO - Started process (PID=1117) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:35:34.182+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:35:34.184+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:35:34.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:35:34.633+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:35:34.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:35:34.635+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:35:34.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.474 seconds
[2024-12-01T00:36:04.853+0000] {processor.py:186} INFO - Started process (PID=1137) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:36:04.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:36:04.856+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:36:04.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:36:05.320+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:36:05.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:36:05.322+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:36:05.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.484 seconds
[2024-12-01T00:36:36.320+0000] {processor.py:186} INFO - Started process (PID=1157) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:36:36.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:36:36.324+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:36:36.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:36:36.786+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:36:36.781+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:36:36.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:36:36.797+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.484 seconds
[2024-12-01T00:37:06.996+0000] {processor.py:186} INFO - Started process (PID=1177) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:37:06.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:37:07.000+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:37:07.000+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:37:07.507+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:37:07.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:37:07.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:37:07.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.530 seconds
[2024-12-01T00:37:37.897+0000] {processor.py:186} INFO - Started process (PID=1197) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:37:37.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:37:37.901+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:37:37.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:37:38.581+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:37:38.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:37:38.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:37:38.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.703 seconds
[2024-12-01T00:38:09.527+0000] {processor.py:186} INFO - Started process (PID=1217) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:38:09.527+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:38:09.530+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:38:09.529+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:38:10.021+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:38:10.016+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:38:10.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:38:10.036+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.515 seconds
[2024-12-01T00:38:40.615+0000] {processor.py:186} INFO - Started process (PID=1237) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:38:40.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:38:40.618+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:38:40.618+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:38:41.154+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:38:41.146+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:38:41.158+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:38:41.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.573 seconds
[2024-12-01T00:39:11.308+0000] {processor.py:186} INFO - Started process (PID=1256) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:39:11.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:39:11.312+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:39:11.312+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:39:11.766+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:39:11.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:39:11.767+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:39:11.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.474 seconds
[2024-12-01T00:39:42.230+0000] {processor.py:186} INFO - Started process (PID=1277) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:39:42.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:39:42.233+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:39:42.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:39:42.693+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:39:42.689+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:39:42.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:39:42.704+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.480 seconds
[2024-12-01T00:40:13.185+0000] {processor.py:186} INFO - Started process (PID=1297) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:40:13.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:40:13.188+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:40:13.188+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:40:13.644+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:40:13.639+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:40:13.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:40:13.654+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.476 seconds
[2024-12-01T00:40:43.874+0000] {processor.py:186} INFO - Started process (PID=1317) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:40:43.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:40:43.877+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:40:43.877+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:40:44.375+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:40:44.370+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:40:44.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:40:44.392+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.523 seconds
[2024-12-01T00:41:14.696+0000] {processor.py:186} INFO - Started process (PID=1337) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:41:14.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:41:14.700+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:41:14.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:41:15.171+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:41:15.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:41:15.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:41:15.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.493 seconds
[2024-12-01T00:41:45.329+0000] {processor.py:186} INFO - Started process (PID=1357) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:41:45.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:41:45.332+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:41:45.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:41:45.793+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:41:45.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:41:45.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:41:45.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.483 seconds
[2024-12-01T00:42:15.891+0000] {processor.py:186} INFO - Started process (PID=1377) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:42:15.892+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:42:15.895+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:42:15.894+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:42:16.335+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:42:16.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:42:16.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:42:16.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.461 seconds
[2024-12-01T00:42:46.505+0000] {processor.py:186} INFO - Started process (PID=1397) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:42:46.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:42:46.509+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:42:46.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:42:46.954+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:42:46.950+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:42:46.956+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:42:46.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.468 seconds
[2024-12-01T00:43:17.189+0000] {processor.py:186} INFO - Started process (PID=1417) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:43:17.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:43:17.194+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:43:17.194+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:43:17.662+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:43:17.657+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:43:17.664+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:43:17.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.496 seconds
[2024-12-01T00:43:47.813+0000] {processor.py:186} INFO - Started process (PID=1437) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:43:47.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:43:47.817+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:43:47.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:43:48.276+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:43:48.272+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:43:48.278+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:43:48.288+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.481 seconds
[2024-12-01T00:44:18.742+0000] {processor.py:186} INFO - Started process (PID=1457) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:44:18.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:44:18.746+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:44:18.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:44:19.199+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:44:19.195+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:44:19.201+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:44:19.215+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.479 seconds
[2024-12-01T00:44:49.645+0000] {processor.py:186} INFO - Started process (PID=1477) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:44:49.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:44:49.649+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:44:49.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:44:50.108+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:44:50.104+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:44:50.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:44:50.126+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.486 seconds
[2024-12-01T00:45:20.719+0000] {processor.py:186} INFO - Started process (PID=1497) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:45:20.720+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:45:20.722+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:45:20.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:45:21.202+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:45:21.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:45:21.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:45:21.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.505 seconds
[2024-12-01T00:45:51.380+0000] {processor.py:186} INFO - Started process (PID=1517) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:45:51.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:45:51.385+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:45:51.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:45:51.870+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:45:51.865+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:45:51.872+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:45:51.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.510 seconds
[2024-12-01T00:46:22.049+0000] {processor.py:186} INFO - Started process (PID=1537) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:46:22.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:46:22.052+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:46:22.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:46:22.662+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:46:22.658+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:46:22.664+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:46:22.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.631 seconds
[2024-12-01T00:46:52.795+0000] {processor.py:186} INFO - Started process (PID=1557) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:46:52.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:46:52.799+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:46:52.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:46:53.269+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:46:53.265+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:46:53.271+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:46:53.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.490 seconds
[2024-12-01T00:47:23.393+0000] {processor.py:186} INFO - Started process (PID=1577) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:47:23.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:47:23.396+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:47:23.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:47:23.861+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:47:23.856+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:47:23.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:47:23.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.486 seconds
[2024-12-01T00:47:54.096+0000] {processor.py:186} INFO - Started process (PID=1597) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:47:54.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:47:54.100+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:47:54.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:47:54.569+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:47:54.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:47:54.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:47:54.581+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.491 seconds
[2024-12-01T00:48:24.804+0000] {processor.py:186} INFO - Started process (PID=1617) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:48:24.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:48:24.807+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:48:24.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:48:25.270+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:48:25.266+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:48:25.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:48:25.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.485 seconds
[2024-12-01T00:48:55.615+0000] {processor.py:186} INFO - Started process (PID=1637) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:48:55.617+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:48:55.619+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:48:55.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:48:56.091+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:48:56.086+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:48:56.092+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:48:56.102+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.492 seconds
[2024-12-01T00:49:27.028+0000] {processor.py:186} INFO - Started process (PID=1657) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:49:27.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:49:27.031+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:49:27.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:49:27.462+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:49:27.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:49:27.463+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:49:27.473+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.450 seconds
[2024-12-01T00:49:57.651+0000] {processor.py:186} INFO - Started process (PID=1677) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:49:57.652+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:49:57.655+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:49:57.654+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:49:58.079+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:49:58.075+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:49:58.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:49:58.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.444 seconds
[2024-12-01T00:50:28.548+0000] {processor.py:186} INFO - Started process (PID=1697) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:50:28.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:50:28.552+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:50:28.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:50:28.997+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:50:28.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:50:28.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:50:29.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.466 seconds
[2024-12-01T00:50:59.313+0000] {processor.py:186} INFO - Started process (PID=1723) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:50:59.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:50:59.316+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:50:59.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:50:59.816+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:50:59.811+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:50:59.817+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:50:59.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.523 seconds
[2024-12-01T00:51:29.939+0000] {processor.py:186} INFO - Started process (PID=1743) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:51:29.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:51:29.943+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:51:29.943+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:51:30.367+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:51:30.362+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:51:30.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:51:30.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.447 seconds
[2024-12-01T00:52:00.919+0000] {processor.py:186} INFO - Started process (PID=1763) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:52:00.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:52:00.923+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:52:00.922+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:52:01.359+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:52:01.354+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:52:01.361+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:52:01.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.459 seconds
[2024-12-01T00:52:31.449+0000] {processor.py:186} INFO - Started process (PID=1782) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:52:31.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:52:31.452+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:52:31.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:52:31.887+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:52:31.883+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:52:31.888+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:52:31.897+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.454 seconds
[2024-12-01T00:53:01.990+0000] {processor.py:186} INFO - Started process (PID=1803) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:53:01.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:53:01.994+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:53:01.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:53:02.434+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:53:02.430+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:53:02.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:53:02.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.462 seconds
[2024-12-01T00:53:33.368+0000] {processor.py:186} INFO - Started process (PID=1823) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:53:33.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:53:33.371+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:53:33.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:53:33.858+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:53:33.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:53:33.860+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:53:33.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.510 seconds
[2024-12-01T00:54:03.988+0000] {processor.py:186} INFO - Started process (PID=1843) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:54:03.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:54:03.991+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:54:03.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:54:04.468+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:54:04.463+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:54:04.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:54:04.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.501 seconds
[2024-12-01T00:54:35.494+0000] {processor.py:186} INFO - Started process (PID=1863) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:54:35.495+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:54:35.498+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:54:35.497+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:54:35.795+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:54:35.791+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:54:35.796+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:54:35.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.319 seconds
[2024-12-01T00:55:06.152+0000] {processor.py:186} INFO - Started process (PID=1883) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:55:06.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:55:06.156+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:55:06.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:55:06.458+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:55:06.453+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:55:06.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:55:06.473+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.326 seconds
[2024-12-01T00:55:36.644+0000] {processor.py:186} INFO - Started process (PID=1903) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:55:36.645+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:55:36.648+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:55:36.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:55:36.967+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:55:36.958+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:55:36.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:55:36.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.342 seconds
[2024-12-01T00:56:07.523+0000] {processor.py:186} INFO - Started process (PID=1923) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:56:07.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:56:07.527+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:56:07.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:56:07.833+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:56:07.828+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:56:07.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:56:07.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.329 seconds
[2024-12-01T00:56:38.083+0000] {processor.py:186} INFO - Started process (PID=1943) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:56:38.084+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:56:38.086+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:56:38.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:56:38.406+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:56:38.401+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:56:38.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:56:38.421+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.344 seconds
[2024-12-01T00:57:08.562+0000] {processor.py:186} INFO - Started process (PID=1963) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:57:08.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:57:08.566+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:57:08.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:57:08.860+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:57:08.855+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:57:08.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:57:08.875+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.318 seconds
[2024-12-01T00:57:39.286+0000] {processor.py:186} INFO - Started process (PID=1983) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:57:39.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:57:39.290+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:57:39.290+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:57:39.595+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:57:39.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:57:39.597+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:57:39.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.328 seconds
[2024-12-01T00:58:10.038+0000] {processor.py:186} INFO - Started process (PID=2003) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:58:10.039+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:58:10.041+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:58:10.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:58:10.324+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:58:10.319+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:58:10.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:58:10.336+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.305 seconds
[2024-12-01T00:58:40.787+0000] {processor.py:186} INFO - Started process (PID=2023) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:58:40.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:58:40.790+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:58:40.790+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:58:41.074+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:58:41.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:58:41.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:58:41.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.306 seconds
[2024-12-01T00:59:11.594+0000] {processor.py:186} INFO - Started process (PID=2043) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:59:11.595+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:59:11.597+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:59:11.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:59:11.887+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:59:11.883+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:59:11.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:59:11.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.312 seconds
[2024-12-01T00:59:42.516+0000] {processor.py:186} INFO - Started process (PID=2063) to work on /opt/airflow/dags/weather.py
[2024-12-01T00:59:42.517+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-01T00:59:42.519+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:59:42.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-01T00:59:42.780+0000] {logging_mixin.py:190} INFO - [2024-12-01T00:59:42.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 19, in <module>
    key_wwo = Variable.get("KEY_API_WWO")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable KEY_API_WWO does not exist'
[2024-12-01T00:59:42.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-01T00:59:42.790+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.278 seconds
